Connection methods
aws/aws-iot-device-sdk-cpp-v2 pull request #655
Opened 2023-11-16 17:28 UTC by alfred2g

Add connection methods code snippets for websocket custom auth, proxy, static credentials, username / password

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-12-01 22:50 UTC, sfod requested changes

2023-12-01 22:50 UTC, sfod commented on samples/utils/CommandLineUtils.cpp
> +        returnData.input_sessionToken = cmdUtils.GetCommandOrDefault(m_cmd_session_token, "");
Debatable: These options should be required when connecting with static creds. For that, a designated function is needed, which might be overkill. That's why debatable.

2023-12-04 15:44 UTC, alfred2g commented on samples/mqtt/websocket_connect/README_username_password.md
> +Utils::cmdData cmdData = Utils::parseSampleInputCustomAuthorizerConnect(argc, argv, &apiHandle);
The same code is present in the builder code

2023-12-04 16:28 UTC, alfred2g commented on samples/mqtt/websocket_connect/README_proxy.md
> +# Websocket Connect with Proxy
there are 2 functions, one that uses proxy and one only username and password

2023-12-04 16:29 UTC, alfred2g commented on samples/mqtt/websocket_connect/README_static_credentials.md
> +./websocket-connect --endpoint <endpoint> --signing_region <signing region>
what do you mean? move the above section down?

2023-12-04 22:45 UTC, sfod commented on samples/mqtt/websocket_connect/README_static_credentials.md
> +./websocket-connect --endpoint <endpoint> --signing_region <signing region>
No, I mean the example should contain these options:
```
./websocket-connect --endpoint <endpoint> --signing_region <signing region> --access_key_id <..> ...
```

2023-12-04 22:45 UTC, sfod commented on samples/mqtt/websocket_connect/README_proxy.md
> +    Utils::cmdData cmdData = Utils::parseSampleInputWebsocketConnect(argc, argv, &apiHandle);
`cmdData` is redefined here, which is a compile-time error. We need to ensure that a code snippet is valid before suggesting it to users

2023-12-04 22:45 UTC, sfod commented on samples/mqtt/websocket_connect/README_proxy.md
> +# Websocket Connect with Proxy
What I meant is that the only difference between the code snippet provided in this readme and the source file is the proxy option is required in one and optional in another.
Maybe instead just describe this option in the main websocket connection readme?

2023-12-04 22:45 UTC, sfod commented on samples/mqtt/websocket_connect/README_proxy.md
> +This sample demonstrates conneting via Websockets using a proxy serverb.
typo: a proxy serverb

2023-12-04 22:45 UTC, sfod commented on samples/mqtt/websocket_connect/README_static_credentials.md
> +This sample makes an MQTT connection via Websockets and then disconnects. On startup, the device connects to the server via Websockets and then disconnects right after. This sample is for reference o
The paragraph should be removed

2023-12-04 22:45 UTC, sfod commented on samples/mqtt/websocket_connect/README_username_password.md
> +./websocket-connect --endpoint <endpoint> --signing_region <signing region>
`custom_auth_*` option should be added here

2023-12-05 01:14 UTC, alfred2g commented on samples/mqtt/websocket_connect/README_proxy.md
> +# Websocket Connect with Proxy
removed it

2023-12-05 01:42 UTC, alfred2g commented on samples/mqtt/websocket_connect/README_custom_auth.md
> +* [Websocket Connect/static credentials](./README_static_credentials.md)
removed

2023-12-08 17:58 UTC, sfod approved these changes

2023-12-08 17:58 UTC, sfod commented on samples/mqtt/websocket_connect/README_custom_auth.md
> +See this page on the documentation for more details and example return result.
`this page on the documentation` should be link, like in this readme: https://github.com/aws/aws-iot-device-sdk-java-v2/tree/main/samples/CustomAuthorizerConnect

2023-12-08 21:44 UTC, merged