Execute jobs when in samples
aws/aws-iot-device-sdk-cpp-v2 pull request #656
Opened 2023-11-20 20:57 UTC by alfred2g

Execute jobs when not in CI

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-12-01 18:18 UTC, alfred2g commented on .github/workflows/ci.yml
> -          python3 ${{ env.CI_UTILS_FOLDER }}/run_sample_ci.py --file ${{ env.CI_SAMPLES_CFG_FOLDER }}/ci_run_jobs_mqtt5_cfg.json
it is exactly like the servicetest one, I will add them back

2023-12-04 21:30 UTC, sfod commented on servicetests/test_cases/test_jobs_execution.py
> +               i = i + 1;
Shouldn't we increment `i` in the Exception block also? Though, the limit should be increased.
Also, maybe it's worth adding a 1-second sleep after each unsuccessful attempt, to not bombard server with requests.

2023-12-04 22:14 UTC, alfred2g commented on servicetests/test_cases/mqtt3_jobs_cfg.json
> +        }
no why?

2023-12-04 22:14 UTC, alfred2g commented on servicetests/test_cases/mqtt5_jobs_cfg.json
> +            "name": "--job_id",
no, why?

2023-12-05 01:49 UTC, alfred2g commented on samples/jobs/mqtt5_job_execution/main.cpp
> +
copied it back here from the other PR

2023-12-11 20:58 UTC, sfod requested changes

2023-12-11 20:58 UTC, sfod commented on samples/jobs/job_execution/main.cpp
I got segfault for this sample. I didn't have any Job configured, maybe this case is not handled?

2023-12-11 21:52 UTC, sfod commented on samples/jobs/describe_job_execution/main.cpp
I see that you removed this sample in the next PR, so nevermind

2023-12-12 20:25 UTC, sfod approved these changes

2023-12-12 20:25 UTC, sfod commented on samples/jobs/mqtt5_job_execution/main.cpp
> +        fprintf(stdout, "Marked job %s currentJobId SUCCEEDED", currentJobId.c_str());
```suggestion
        fprintf(stdout, "Marked job %s %s\n", currentJobId.c_str(), JobStatusMarshaller::ToString(status));
```

2023-12-12 20:35 UTC, sfod commented on samples/utils/CommandLineUtils.cpp
> +        returnData.input_jobId = cmdUtils.GetCommandOrDefault(m_cmd_job_id, "1");
Debatable: Set to empty string by default. And in the samples request for a job description only if jobId is set.

2023-12-13 00:28 UTC, merged